name: CI

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libfluidsynth-dev
          # Only needed when gpsd is added to the build.
          # sudo apt-get install libgps-dev
          
      - name: Install test dependencies
        run: sudo apt install socat

      - name: Create Build Environment & configure CMake
        working-directory: ${{runner.workspace}}/libromi
        run: |
          mkdir build_tests
          cd build_tests
          cmake ..

      - name: Build
        working-directory: ${{runner.workspace}}/libromi
        run: |
          cd build_tests
          make -j4

      - name: Test
        working-directory: ${{runner.workspace}}/libromi
        run: |
          cd build_tests
          ctest -V -R romi

      - name: debug_path_build
        working-directory: ${{runner.workspace}}/libromi
        run: |
          cd build_tests
          echo "pwd build tests"
          pwd
          echo "ls build tests"
          ls -lart

      - name: Upload coverage to Codecov
        working-directory: ${{runner.workspace}}/libromi
        run: bash <(curl -s https://codecov.io/bash)
